[plugin]
repository = "https://github.com/AtmoOmen/CurrencyTracker.git"
commit = "030fdc78fa46737079d6d4f9c6b61b73208427ba"
owners = ["AtmoOmen"]
project_path = "CurrencyTracker"
changelog = """
Fixed the issue of failed multi-chara functionality
"""
